### PR TITLE
Added in queues to the dictionary

### PR DESCRIPTION
**Pull request by tmloupe**
Because we need queues!

### CODE REVIEW

**Comment by cam-carter** [comment]
Looks good to me! However, I do have a question about the wait queue.  Wouldn't waiting processes just gut moved to the bottom of the ready queue, or does there need to be a separate queue for processes going through their wait time not burst?

**Comment by tmloupe** [comment]
There has to be a separate wait queue. If a process is finished its first CPU burst, then it may have to go into the waiting queue before it can complete another CPU burst. In your proposed scenario, those processes are only moved to the bottom if it cannot complete it in the specific time quantum.

**Comment by cam-carter** [comment]
Wasn't a proposition just a question! 😄 But yah I totally forgot about the time quantum. So here's another question.  While a process is bursting and that variable is being decremented, can the counter on the wait time for another process also decrease?  The pains of not paying attention in class... This is really not that bad to implement; I can see it coming together in my noggin.

**Comment by tmloupe** [comment]
Yes. Processes in the waiting queue will have their wait time decremented.

**Pull request merged**
